# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      - "master"  # Aktivira workflow kada se napravi push na master branch
  pull_request:
    branches:
      - "master"  # Aktivira workflow kada se otvori PR prema master branchu

jobs:
  build:
    runs-on: ubuntu-latest  # Definiše operativni sistem za CI proces

    steps:
      - uses: actions/checkout@v4  # Preuzima kod sa repozitorijuma
      - name: Install dependencies
        run: npm install  # Instalira sve zavisnosti
      - name: Build app
        run: npm run build  # Kreira build za aplikaciju
      - name: Run tests (ako postoje)
        run: npm test  # Pokreće testove (ako ih imate)

